// Code generated DO NOT EDIT

package cmds

import "testing"

func timeseries0(s Builder) {
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateBlock().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateBlock().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateFirst().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateFirst().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateLast().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateLast().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateMin().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateMin().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateMax().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateMax().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateSum().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).OnDuplicateSum().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().ChunkSize(1).GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().OnDuplicateBlock().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().OnDuplicateFirst().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().OnDuplicateLast().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().OnDuplicateMin().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().OnDuplicateMax().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().OnDuplicateSum().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingUncompressed().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().ChunkSize(1).GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().OnDuplicateBlock().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().OnDuplicateFirst().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().OnDuplicateLast().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().OnDuplicateMin().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().OnDuplicateMax().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().OnDuplicateSum().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).EncodingCompressed().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).ChunkSize(1).GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).OnDuplicateBlock().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).OnDuplicateFirst().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).OnDuplicateLast().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).OnDuplicateMin().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).OnDuplicateMax().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).OnDuplicateSum().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Retention(1).GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).EncodingUncompressed().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).EncodingCompressed().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).ChunkSize(1).GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).OnDuplicateBlock().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).OnDuplicateFirst().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).OnDuplicateLast().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).OnDuplicateMin().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).OnDuplicateMax().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).OnDuplicateSum().GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAdd().Key("1").Timestamp(1).Value(1).GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyBlock().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyBlock().GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyFirst().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyFirst().GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyLast().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyLast().GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyMin().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyMin().GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyMax().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicyMax().GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicySum().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).DuplicatePolicySum().GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).ChunkSize(1).GetArgs()
	s.TsAlter().Key("1").Retention(1).DuplicatePolicyBlock().GetArgs()
	s.TsAlter().Key("1").Retention(1).DuplicatePolicyFirst().GetArgs()
	s.TsAlter().Key("1").Retention(1).DuplicatePolicyLast().GetArgs()
	s.TsAlter().Key("1").Retention(1).DuplicatePolicyMin().GetArgs()
	s.TsAlter().Key("1").Retention(1).DuplicatePolicyMax().GetArgs()
	s.TsAlter().Key("1").Retention(1).DuplicatePolicySum().GetArgs()
	s.TsAlter().Key("1").Retention(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").Retention(1).GetArgs()
	s.TsAlter().Key("1").ChunkSize(1).GetArgs()
	s.TsAlter().Key("1").DuplicatePolicyBlock().GetArgs()
	s.TsAlter().Key("1").DuplicatePolicyFirst().GetArgs()
	s.TsAlter().Key("1").DuplicatePolicyLast().GetArgs()
	s.TsAlter().Key("1").DuplicatePolicyMin().GetArgs()
	s.TsAlter().Key("1").DuplicatePolicyMax().GetArgs()
	s.TsAlter().Key("1").DuplicatePolicySum().GetArgs()
	s.TsAlter().Key("1").Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsAlter().Key("1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyBlock().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyBlock().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyFirst().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyFirst().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyLast().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyLast().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyMin().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyMin().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyMax().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicyMax().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicySum().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).DuplicatePolicySum().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().ChunkSize(1).GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().DuplicatePolicyBlock().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().DuplicatePolicyFirst().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().DuplicatePolicyLast().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().DuplicatePolicyMin().GetArgs()
}

func timeseries1(s Builder) {
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().DuplicatePolicyMax().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().DuplicatePolicySum().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingUncompressed().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().ChunkSize(1).GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().DuplicatePolicyBlock().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().DuplicatePolicyFirst().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().DuplicatePolicyLast().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().DuplicatePolicyMin().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().DuplicatePolicyMax().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().DuplicatePolicySum().GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).EncodingCompressed().GetArgs()
	s.TsCreate().Key("1").Retention(1).ChunkSize(1).GetArgs()
	s.TsCreate().Key("1").Retention(1).DuplicatePolicyBlock().GetArgs()
	s.TsCreate().Key("1").Retention(1).DuplicatePolicyFirst().GetArgs()
	s.TsCreate().Key("1").Retention(1).DuplicatePolicyLast().GetArgs()
	s.TsCreate().Key("1").Retention(1).DuplicatePolicyMin().GetArgs()
	s.TsCreate().Key("1").Retention(1).DuplicatePolicyMax().GetArgs()
	s.TsCreate().Key("1").Retention(1).DuplicatePolicySum().GetArgs()
	s.TsCreate().Key("1").Retention(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").Retention(1).GetArgs()
	s.TsCreate().Key("1").EncodingUncompressed().GetArgs()
	s.TsCreate().Key("1").EncodingCompressed().GetArgs()
	s.TsCreate().Key("1").ChunkSize(1).GetArgs()
	s.TsCreate().Key("1").DuplicatePolicyBlock().GetArgs()
	s.TsCreate().Key("1").DuplicatePolicyFirst().GetArgs()
	s.TsCreate().Key("1").DuplicatePolicyLast().GetArgs()
	s.TsCreate().Key("1").DuplicatePolicyMin().GetArgs()
	s.TsCreate().Key("1").DuplicatePolicyMax().GetArgs()
	s.TsCreate().Key("1").DuplicatePolicySum().GetArgs()
	s.TsCreate().Key("1").Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsCreate().Key("1").GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationAvg().Bucketduration(1).Aligntimestamp(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationAvg().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationSum().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationMin().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationMax().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationRange().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationCount().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationFirst().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationLast().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationStdP().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationStdS().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationVarP().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationVarS().Bucketduration(1).GetArgs()
	s.TsCreaterule().Sourcekey("1").Destkey("1").AggregationTwa().Bucketduration(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().ChunkSize(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().ChunkSize(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Retention(1).ChunkSize(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Retention(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Retention(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Uncompressed().GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).ChunkSize(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsDecrby().Key("1").Value(1).Timestamp(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Retention(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Uncompressed().GetArgs()
	s.TsDecrby().Key("1").Value(1).ChunkSize(1).GetArgs()
	s.TsDecrby().Key("1").Value(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsDecrby().Key("1").Value(1).GetArgs()
	s.TsDel().Key("1").FromTimestamp(1).ToTimestamp(1).GetArgs()
	s.TsDeleterule().Sourcekey("1").Destkey("1").GetArgs()
	s.TsGet().Key("1").Latest().GetArgs()
	s.TsGet().Key("1").GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().ChunkSize(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().ChunkSize(1).GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Retention(1).Uncompressed().GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Retention(1).ChunkSize(1).GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Retention(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Retention(1).GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Uncompressed().GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).ChunkSize(1).GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsIncrby().Key("1").Value(1).Timestamp(1).GetArgs()
	s.TsIncrby().Key("1").Value(1).Retention(1).GetArgs()
	s.TsIncrby().Key("1").Value(1).Uncompressed().GetArgs()
	s.TsIncrby().Key("1").Value(1).ChunkSize(1).GetArgs()
	s.TsIncrby().Key("1").Value(1).Labels().Labels("1", "1").Labels("1", "1").GetArgs()
	s.TsIncrby().Key("1").Value(1).GetArgs()
	s.TsInfo().Key("1").Debug("1").GetArgs()
	s.TsInfo().Key("1").GetArgs()
	s.TsMadd().KeyTimestampValue().KeyTimestampValue("1", 1, 1).KeyTimestampValue("1", 1, 1).GetArgs()
	s.TsMget().Latest().Withlabels().Filter("1").Filter("1").GetArgs()
	s.TsMget().Latest().SelectedLabels([]interface{}{"1"}).Filter("1").Filter("1").GetArgs()
	s.TsMget().Latest().Filter("1").Filter("1").GetArgs()
	s.TsMget().Withlabels().Filter("1").Filter("1").GetArgs()
	s.TsMget().SelectedLabels([]interface{}{"1"}).Filter("1").Filter("1").GetArgs()
	s.TsMget().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").Groupby("1", "1", "1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
}

func timeseries2(s Builder) {
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
}

func timeseries3(s Builder) {
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Latest().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrange().Fromtimestamp(1).Totimestamp(1).Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").Groupby("1", "1", "1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).SelectedLabels([]interface{}{"1"}).Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
}

func timeseries4(s Builder) {
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Latest().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).FilterByValue(1, 1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Withlabels().Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).SelectedLabels([]interface{}{"1"}).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationSum().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationMin().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationMax().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationRange().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationCount().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationFirst().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationLast().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationStdP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationStdS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationVarP().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationVarS().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).AggregationTwa().Bucketduration(1).Buckettimestamp("1").Empty().Filter("1").Filter("1").GetArgs()
	s.TsMrevrange().Fromtimestamp(1).Totimestamp(1).Filter("1").Filter("1").GetArgs()
	s.TsQueryindex().Filter("1").Filter("1").GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Empty().GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationSum().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationMin().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationMax().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationRange().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationCount().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationLast().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationMin().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationCount().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Align("1").GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMin().Bucketduration(1).GetArgs()
}

func timeseries5(s Builder) {
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationCount().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Count(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Align("1").GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMin().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationCount().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByValue(1, 1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().Count(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().Align("1").GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationSum().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationMin().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationMax().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationRange().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationCount().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationLast().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).FilterByTs(1).FilterByTs(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).FilterByValue(1, 1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Count(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).Align("1").GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationMin().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationCount().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRange().Key("1").Fromtimestamp(1).Totimestamp(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").Empty().GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Buckettimestamp("1").GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).Empty().GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationSum().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationMin().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationMax().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationRange().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationCount().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationLast().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).Align("1").GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationMin().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationCount().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Count(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).Align("1").GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMin().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationCount().Bucketduration(1).GetArgs()
}

func timeseries6(s Builder) {
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).FilterByValue(1, 1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Count(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).Align("1").GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMin().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationCount().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByTs(1).FilterByTs(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().FilterByValue(1, 1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().Count(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().Align("1").GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationSum().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationMin().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationMax().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationRange().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationCount().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationLast().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Latest().GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).FilterByTs(1).FilterByTs(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).FilterByValue(1, 1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Count(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).Align("1").GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationAvg().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationSum().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationMin().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationMax().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationRange().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationCount().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationFirst().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationLast().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationStdP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationStdS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationVarP().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationVarS().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).AggregationTwa().Bucketduration(1).GetArgs()
	s.TsRevrange().Key("1").Fromtimestamp(1).Totimestamp(1).GetArgs()
}

func TestCommand_timeseries(t *testing.T) {
	t.Run("0", func(t *testing.T) { timeseries0(Builder{}) })
	t.Run("1", func(t *testing.T) { timeseries1(Builder{}) })
	t.Run("2", func(t *testing.T) { timeseries2(Builder{}) })
	t.Run("3", func(t *testing.T) { timeseries3(Builder{}) })
	t.Run("4", func(t *testing.T) { timeseries4(Builder{}) })
	t.Run("5", func(t *testing.T) { timeseries5(Builder{}) })
	t.Run("6", func(t *testing.T) { timeseries6(Builder{}) })
}
