// Code generated DO NOT EDIT

package cmds

import "testing"

func json0(s Builder) {
	s.JsonArrappend().Key("1").Path("1").Value("1").Value("1").GetArgs()
	s.JsonArrappend().Key("1").Value("1").Value("1").GetArgs()
	s.JsonArrindex().Key("1").Path("1").Value("1").Start(1).Stop(1).GetArgs()
	s.JsonArrindex().Key("1").Path("1").Value("1").Start(1).GetArgs()
	s.JsonArrindex().Key("1").Path("1").Value("1").GetArgs()
	s.JsonArrinsert().Key("1").Path("1").Index(1).Value("1").Value("1").GetArgs()
	s.JsonArrlen().Key("1").Path("1").GetArgs()
	s.JsonArrlen().Key("1").GetArgs()
	s.JsonArrpop().Key("1").Path("1").Index(1).GetArgs()
	s.JsonArrpop().Key("1").Path("1").GetArgs()
	s.JsonArrpop().Key("1").GetArgs()
	s.JsonArrtrim().Key("1").Path("1").Start(1).Stop(1).GetArgs()
	s.JsonClear().Key("1").Path("1").GetArgs()
	s.JsonClear().Key("1").GetArgs()
	s.JsonDebugHelp().GetArgs()
	s.JsonDebugMemory().Key("1").Path("1").GetArgs()
	s.JsonDebugMemory().Key("1").GetArgs()
	s.JsonDel().Key("1").Path("1").GetArgs()
	s.JsonDel().Key("1").GetArgs()
	s.JsonForget().Key("1").Path("1").GetArgs()
	s.JsonForget().Key("1").GetArgs()
	s.JsonGet().Key("1").Indent("1").Newline("1").Space("1").Path("1").Path("1").GetArgs()
	s.JsonGet().Key("1").Indent("1").Newline("1").Space("1").GetArgs()
	s.JsonGet().Key("1").Indent("1").Newline("1").Path("1").Path("1").GetArgs()
	s.JsonGet().Key("1").Indent("1").Newline("1").GetArgs()
	s.JsonGet().Key("1").Indent("1").Space("1").GetArgs()
	s.JsonGet().Key("1").Indent("1").Path("1").Path("1").GetArgs()
	s.JsonGet().Key("1").Indent("1").GetArgs()
	s.JsonGet().Key("1").Newline("1").GetArgs()
	s.JsonGet().Key("1").Space("1").GetArgs()
	s.JsonGet().Key("1").Path("1").Path("1").GetArgs()
	s.JsonGet().Key("1").GetArgs()
	s.JsonMerge().Key("1").Path("1").Value("1").GetArgs()
	s.JsonMget().Key("1").Key("1").Path("1").GetArgs()
	s.JsonMset().Key("1").Path("1").Value("1").Key("1").Path("1").Value("1").GetArgs()
	s.JsonNumincrby().Key("1").Path("1").Value(1).GetArgs()
	s.JsonNummultby().Key("1").Path("1").Value(1).GetArgs()
	s.JsonObjkeys().Key("1").Path("1").GetArgs()
	s.JsonObjkeys().Key("1").GetArgs()
	s.JsonObjlen().Key("1").Path("1").GetArgs()
	s.JsonObjlen().Key("1").GetArgs()
	s.JsonResp().Key("1").Path("1").GetArgs()
	s.JsonResp().Key("1").GetArgs()
	s.JsonSet().Key("1").Path("1").Value("1").Nx().GetArgs()
	s.JsonSet().Key("1").Path("1").Value("1").Xx().GetArgs()
	s.JsonSet().Key("1").Path("1").Value("1").GetArgs()
	s.JsonStrappend().Key("1").Path("1").Value("1").GetArgs()
	s.JsonStrappend().Key("1").Value("1").GetArgs()
	s.JsonStrlen().Key("1").Path("1").GetArgs()
	s.JsonStrlen().Key("1").GetArgs()
	s.JsonToggle().Key("1").Path("1").GetArgs()
	s.JsonType().Key("1").Path("1").GetArgs()
	s.JsonType().Key("1").GetArgs()
}

func TestCommand_json(t *testing.T) {
	t.Run("0", func(t *testing.T) { json0(Builder{}) })
}
